/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Set options for SET command */
export interface SetOptions {
  /** Expiration in seconds */
  ex?: number
  /** Expiration in milliseconds */
  px?: number
  /** Only set if key does not exist */
  nx?: boolean
  /** Only set if key exists */
  xx?: boolean
}
/** Sorted set member with score */
export interface ZMember {
  score: number
  member: Buffer
}
export type JsDb = RedliteDb
/** Redlite database - Redis API with SQLite durability */
export declare class RedliteDb {
  /**
   * Open a database at the given path
   * Use ":memory:" for an in-memory database
   */
  constructor(path: string)
  /** Open an in-memory database */
  static openMemory(): JsDb
  /** Open a database with custom cache size in MB */
  static openWithCache(path: string, cacheMb: number): JsDb
  /** Get the value of a key */
  get(key: string): Buffer | null
  /** Set a key-value pair with optional expiration */
  set(key: string, value: Buffer, options?: SetOptions | undefined | null): boolean
  /** Set key with expiration in seconds */
  setex(key: string, seconds: number, value: Buffer): boolean
  /** Set key with expiration in milliseconds */
  psetex(key: string, milliseconds: number, value: Buffer): boolean
  /** Get and delete a key */
  getdel(key: string): Buffer | null
  /** Append value to a key */
  append(key: string, value: Buffer): number
  /** Get string length of a key */
  strlen(key: string): number
  /** Get substring of a string value */
  getrange(key: string, start: number, end: number): Buffer
  /** Overwrite part of a string at key starting at offset */
  setrange(key: string, offset: number, value: Buffer): number
  /** Increment the integer value of a key by one */
  incr(key: string): number
  /** Decrement the integer value of a key by one */
  decr(key: string): number
  /** Increment the integer value of a key by amount */
  incrby(key: string, increment: number): number
  /** Decrement the integer value of a key by amount */
  decrby(key: string, decrement: number): number
  /** Increment the float value of a key by amount */
  incrbyfloat(key: string, increment: number): number
  /** Get values of multiple keys */
  mget(keys: Array<string>): Array<Buffer | undefined | null>
  /** Set multiple key-value pairs atomically */
  mset(pairs: Array<Array<Buffer>>): boolean
  /** Delete one or more keys */
  del(keys: Array<string>): number
  /** Check if keys exist */
  exists(keys: Array<string>): number
  /** Get the type of a key */
  type(key: string): string
  /** Get TTL in seconds */
  ttl(key: string): number
  /** Get TTL in milliseconds */
  pttl(key: string): number
  /** Set expiration in seconds */
  expire(key: string, seconds: number): boolean
  /** Set expiration in milliseconds */
  pexpire(key: string, milliseconds: number): boolean
  /** Set expiration at Unix timestamp (seconds) */
  expireat(key: string, unixTime: number): boolean
  /** Set expiration at Unix timestamp (milliseconds) */
  pexpireat(key: string, unixTimeMs: number): boolean
  /** Remove expiration from a key */
  persist(key: string): boolean
  /** Rename a key */
  rename(key: string, newkey: string): boolean
  /** Rename a key only if newkey does not exist */
  renamenx(key: string, newkey: string): boolean
  /** Find all keys matching a pattern */
  keys(pattern?: string | undefined | null): Array<string>
  /** Get the number of keys in the database */
  dbsize(): number
  /** Delete all keys in the current database */
  flushdb(): boolean
  /** Select a database by index */
  select(db: number): boolean
  /** Set a single hash field */
  hset(key: string, field: string, value: Buffer): number
  /** Get a hash field value */
  hget(key: string, field: string): Buffer | null
  /** Delete hash fields */
  hdel(key: string, fields: Array<string>): number
  /** Check if hash field exists */
  hexists(key: string, field: string): boolean
  /** Get number of fields in a hash */
  hlen(key: string): number
  /** Get all field names in a hash */
  hkeys(key: string): Array<string>
  /** Get all values in a hash */
  hvals(key: string): Array<Buffer>
  /** Increment hash field by integer */
  hincrby(key: string, field: string, increment: number): number
  /** Get all fields and values in a hash */
  hgetall(key: string): Array<Array<Buffer>>
  /** Get values of multiple hash fields */
  hmget(key: string, fields: Array<string>): Array<Buffer | undefined | null>
  /** Push values to the left of a list */
  lpush(key: string, values: Array<Buffer>): number
  /** Push values to the right of a list */
  rpush(key: string, values: Array<Buffer>): number
  /** Pop values from the left of a list */
  lpop(key: string, count?: number | undefined | null): Array<Buffer>
  /** Pop values from the right of a list */
  rpop(key: string, count?: number | undefined | null): Array<Buffer>
  /** Get list length */
  llen(key: string): number
  /** Get a range of elements from a list */
  lrange(key: string, start: number, stop: number): Array<Buffer>
  /** Get element at index in a list */
  lindex(key: string, index: number): Buffer | null
  /** Add members to a set */
  sadd(key: string, members: Array<Buffer>): number
  /** Remove members from a set */
  srem(key: string, members: Array<Buffer>): number
  /** Get all members of a set */
  smembers(key: string): Array<Buffer>
  /** Check if member is in a set */
  sismember(key: string, member: Buffer): boolean
  /** Get number of members in a set */
  scard(key: string): number
  /** Add members with scores to a sorted set */
  zadd(key: string, members: Array<ZMember>): number
  /** Remove members from a sorted set */
  zrem(key: string, members: Array<Buffer>): number
  /** Get score of a member in a sorted set */
  zscore(key: string, member: Buffer): number | null
  /** Get number of members in a sorted set */
  zcard(key: string): number
  /** Count members in a sorted set within a score range */
  zcount(key: string, min: number, max: number): number
  /** Increment score of a member in a sorted set */
  zincrby(key: string, increment: number, member: Buffer): number
  /** Get a range of members from a sorted set by index */
  zrange(key: string, start: number, stop: number, withScores?: boolean | undefined | null): Array<Buffer>
  /** Get a range of members from a sorted set by index, in reverse order */
  zrevrange(key: string, start: number, stop: number, withScores?: boolean | undefined | null): Array<Buffer>
  /** Run SQLite VACUUM to reclaim space */
  vacuum(): number
}
