/* Auto-generated C bindings for redlite
 * Do not edit manually - regenerate with: cbindgen -c cbindgen.toml -o redlite.h
 */


#ifndef REDLITE_H
#define REDLITE_H

/* Warning: this file is autogenerated. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to a redlite database
 */
typedef struct RedliteDb RedliteDb;

/**
 * Result of operations that return bytes
 */
typedef struct RedliteBytes {
  uint8_t *data;
  size_t len;
} RedliteBytes;

/**
 * Result of operations that return a string array
 */
typedef struct RedliteStringArray {
  char **strings;
  size_t len;
} RedliteStringArray;

/**
 * Result of operations that return bytes array
 */
typedef struct RedliteBytesArray {
  struct RedliteBytes *items;
  size_t len;
} RedliteBytesArray;

/**
 * Sorted set member
 */
typedef struct RedliteZMember {
  double score;
  const uint8_t *member;
  size_t member_len;
} RedliteZMember;

/**
 * Key-value pair for hash operations
 */
typedef struct RedliteKV {
  const char *key;
  const uint8_t *value;
  size_t value_len;
} RedliteKV;

/**
 * Open a database at the given path
 *
 * Returns NULL on error. Call `redlite_last_error` for details.
 */
struct RedliteDb *redlite_open(const char *path);

/**
 * Open an in-memory database
 */
struct RedliteDb *redlite_open_memory(void);

/**
 * Open a database with custom cache size
 */
struct RedliteDb *redlite_open_with_cache(const char *path, int64_t cache_mb);

/**
 * Close a database and free resources
 */
void redlite_close(struct RedliteDb *db);

/**
 * Get the last error message (NULL if no error)
 */
char *redlite_last_error(void);

/**
 * Free a string returned by redlite functions
 */
void redlite_free_string(char *s);

/**
 * Free bytes returned by redlite functions
 */
void redlite_free_bytes(struct RedliteBytes bytes);

/**
 * Free a string array returned by redlite functions
 */
void redlite_free_string_array(struct RedliteStringArray arr);

/**
 * Free a bytes array returned by redlite functions
 */
void redlite_free_bytes_array(struct RedliteBytesArray arr);

/**
 * GET key
 */
struct RedliteBytes redlite_get(struct RedliteDb *db, const char *key);

/**
 * SET key value [ttl_seconds]
 * Returns 0 on success, -1 on error
 */
int redlite_set(struct RedliteDb *db,
                const char *key,
                const uint8_t *value,
                size_t value_len,
                int64_t ttl_seconds);

/**
 * SETEX key seconds value
 */
int redlite_setex(struct RedliteDb *db,
                  const char *key,
                  int64_t seconds,
                  const uint8_t *value,
                  size_t value_len);

/**
 * PSETEX key milliseconds value
 */
int redlite_psetex(struct RedliteDb *db,
                   const char *key,
                   int64_t milliseconds,
                   const uint8_t *value,
                   size_t value_len);

/**
 * GETDEL key
 */
struct RedliteBytes redlite_getdel(struct RedliteDb *db, const char *key);

/**
 * APPEND key value
 * Returns new length, or -1 on error
 */
int64_t redlite_append(struct RedliteDb *db,
                       const char *key,
                       const uint8_t *value,
                       size_t value_len);

/**
 * STRLEN key
 */
int64_t redlite_strlen(struct RedliteDb *db, const char *key);

/**
 * GETRANGE key start end
 */
struct RedliteBytes redlite_getrange(struct RedliteDb *db,
                                     const char *key,
                                     int64_t start,
                                     int64_t end);

/**
 * SETRANGE key offset value
 */
int64_t redlite_setrange(struct RedliteDb *db,
                         const char *key,
                         int64_t offset,
                         const uint8_t *value,
                         size_t value_len);

/**
 * INCR key
 */
int64_t redlite_incr(struct RedliteDb *db, const char *key);

/**
 * DECR key
 */
int64_t redlite_decr(struct RedliteDb *db, const char *key);

/**
 * INCRBY key increment
 */
int64_t redlite_incrby(struct RedliteDb *db, const char *key, int64_t increment);

/**
 * DECRBY key decrement
 */
int64_t redlite_decrby(struct RedliteDb *db, const char *key, int64_t decrement);

/**
 * INCRBYFLOAT key increment
 * Returns result as string (caller must free), NULL on error
 */
char *redlite_incrbyfloat(struct RedliteDb *db, const char *key, double increment);

/**
 * MGET key [key ...]
 */
struct RedliteBytesArray redlite_mget(struct RedliteDb *db,
                                      const char *const *keys,
                                      size_t keys_len);

/**
 * MSET key value [key value ...]
 */
int redlite_mset(struct RedliteDb *db, const struct RedliteKV *pairs, size_t pairs_len);

/**
 * DEL key [key ...]
 * Returns number of keys deleted
 */
int64_t redlite_del(struct RedliteDb *db, const char *const *keys, size_t keys_len);

/**
 * EXISTS key [key ...]
 */
int64_t redlite_exists(struct RedliteDb *db, const char *const *keys, size_t keys_len);

/**
 * TYPE key
 * Returns type string (caller must free), NULL if key doesn't exist
 */
char *redlite_type(struct RedliteDb *db, const char *key);

/**
 * TTL key
 * Returns -2 if key doesn't exist, -1 if no TTL, otherwise seconds
 */
int64_t redlite_ttl(struct RedliteDb *db, const char *key);

/**
 * PTTL key
 */
int64_t redlite_pttl(struct RedliteDb *db, const char *key);

/**
 * EXPIRE key seconds
 */
int redlite_expire(struct RedliteDb *db, const char *key, int64_t seconds);

/**
 * PEXPIRE key milliseconds
 */
int redlite_pexpire(struct RedliteDb *db, const char *key, int64_t milliseconds);

/**
 * EXPIREAT key unix_timestamp
 */
int redlite_expireat(struct RedliteDb *db, const char *key, int64_t unix_seconds);

/**
 * PEXPIREAT key unix_timestamp_ms
 */
int redlite_pexpireat(struct RedliteDb *db, const char *key, int64_t unix_ms);

/**
 * PERSIST key
 */
int redlite_persist(struct RedliteDb *db, const char *key);

/**
 * RENAME key newkey
 */
int redlite_rename(struct RedliteDb *db, const char *key, const char *newkey);

/**
 * RENAMENX key newkey
 */
int redlite_renamenx(struct RedliteDb *db, const char *key, const char *newkey);

/**
 * KEYS pattern
 */
struct RedliteStringArray redlite_keys(struct RedliteDb *db, const char *pattern);

/**
 * DBSIZE
 */
int64_t redlite_dbsize(struct RedliteDb *db);

/**
 * FLUSHDB
 */
int redlite_flushdb(struct RedliteDb *db);

/**
 * SELECT db
 */
int redlite_select(struct RedliteDb *db, int db_num);

/**
 * HSET key field value [field value ...]
 */
int64_t redlite_hset(struct RedliteDb *db,
                     const char *key,
                     const char *const *fields,
                     const struct RedliteBytes *values,
                     size_t count);

/**
 * HGET key field
 */
struct RedliteBytes redlite_hget(struct RedliteDb *db, const char *key, const char *field);

/**
 * HDEL key field [field ...]
 */
int64_t redlite_hdel(struct RedliteDb *db,
                     const char *key,
                     const char *const *fields,
                     size_t fields_len);

/**
 * HEXISTS key field
 */
int redlite_hexists(struct RedliteDb *db, const char *key, const char *field);

/**
 * HLEN key
 */
int64_t redlite_hlen(struct RedliteDb *db, const char *key);

/**
 * HKEYS key
 */
struct RedliteStringArray redlite_hkeys(struct RedliteDb *db, const char *key);

/**
 * HVALS key
 */
struct RedliteBytesArray redlite_hvals(struct RedliteDb *db, const char *key);

/**
 * HINCRBY key field increment
 */
int64_t redlite_hincrby(struct RedliteDb *db,
                        const char *key,
                        const char *field,
                        int64_t increment);

/**
 * HGETALL key
 * Returns alternating field-value pairs
 */
struct RedliteBytesArray redlite_hgetall(struct RedliteDb *db, const char *key);

/**
 * HMGET key field [field ...]
 */
struct RedliteBytesArray redlite_hmget(struct RedliteDb *db,
                                       const char *key,
                                       const char *const *fields,
                                       size_t fields_len);

/**
 * LPUSH key value [value ...]
 */
int64_t redlite_lpush(struct RedliteDb *db,
                      const char *key,
                      const struct RedliteBytes *values,
                      size_t values_len);

/**
 * RPUSH key value [value ...]
 */
int64_t redlite_rpush(struct RedliteDb *db,
                      const char *key,
                      const struct RedliteBytes *values,
                      size_t values_len);

/**
 * LPOP key [count]
 */
struct RedliteBytesArray redlite_lpop(struct RedliteDb *db, const char *key, size_t count);

/**
 * RPOP key [count]
 */
struct RedliteBytesArray redlite_rpop(struct RedliteDb *db, const char *key, size_t count);

/**
 * LLEN key
 */
int64_t redlite_llen(struct RedliteDb *db, const char *key);

/**
 * LRANGE key start stop
 */
struct RedliteBytesArray redlite_lrange(struct RedliteDb *db,
                                        const char *key,
                                        int64_t start,
                                        int64_t stop);

/**
 * LINDEX key index
 */
struct RedliteBytes redlite_lindex(struct RedliteDb *db, const char *key, int64_t index);

/**
 * SADD key member [member ...]
 */
int64_t redlite_sadd(struct RedliteDb *db,
                     const char *key,
                     const struct RedliteBytes *members,
                     size_t members_len);

/**
 * SREM key member [member ...]
 */
int64_t redlite_srem(struct RedliteDb *db,
                     const char *key,
                     const struct RedliteBytes *members,
                     size_t members_len);

/**
 * SMEMBERS key
 */
struct RedliteBytesArray redlite_smembers(struct RedliteDb *db, const char *key);

/**
 * SISMEMBER key member
 */
int redlite_sismember(struct RedliteDb *db,
                      const char *key,
                      const uint8_t *member,
                      size_t member_len);

/**
 * SCARD key
 */
int64_t redlite_scard(struct RedliteDb *db, const char *key);

/**
 * ZADD key score member [score member ...]
 */
int64_t redlite_zadd(struct RedliteDb *db,
                     const char *key,
                     const struct RedliteZMember *members,
                     size_t members_len);

/**
 * ZREM key member [member ...]
 */
int64_t redlite_zrem(struct RedliteDb *db,
                     const char *key,
                     const struct RedliteBytes *members,
                     size_t members_len);

/**
 * ZSCORE key member
 * Returns NaN if not found or on error
 */
double redlite_zscore(struct RedliteDb *db,
                      const char *key,
                      const uint8_t *member,
                      size_t member_len);

/**
 * ZCARD key
 */
int64_t redlite_zcard(struct RedliteDb *db, const char *key);

/**
 * ZCOUNT key min max
 */
int64_t redlite_zcount(struct RedliteDb *db, const char *key, double min, double max);

/**
 * ZINCRBY key increment member
 */
double redlite_zincrby(struct RedliteDb *db,
                       const char *key,
                       double increment,
                       const uint8_t *member,
                       size_t member_len);

/**
 * ZRANGE key start stop [withscores]
 * If withscores is true, returns alternating member-score pairs
 */
struct RedliteBytesArray redlite_zrange(struct RedliteDb *db,
                                        const char *key,
                                        int64_t start,
                                        int64_t stop,
                                        int with_scores);

/**
 * ZREVRANGE key start stop [withscores]
 * If withscores is true, returns alternating member-score pairs
 */
struct RedliteBytesArray redlite_zrevrange(struct RedliteDb *db,
                                           const char *key,
                                           int64_t start,
                                           int64_t stop,
                                           int with_scores);

/**
 * VACUUM - compact the database
 */
int64_t redlite_vacuum(struct RedliteDb *db);

/**
 * Get library version
 */
char *redlite_version(void);

#endif /* REDLITE_H */
