# Redlite LOLCODE SDK Makefile
# CAN HAS BUILD SYSTEM?

.PHONY: all build test clean help hai kthxbye

all: hai build

hai:
	@echo "HAI 1.2"
	@echo "  CAN HAS REDLITE?"
	@echo "  VISIBLE \"WELCOM 2 REDLITE LOLCODE SDK\""

build:
	@echo "BTW Buildin LOLCODE SDK..."
	@echo "BTW Actually there iz nothin 2 build"
	@echo "BTW LOLCODE iz interpreted liek ur life choicez"
	@echo "BUILD COMPLETE! KTHX"

test:
	@echo "IM IN YR TESTS, TESTIN YR DATABASE"
	@if command -v lci >/dev/null 2>&1; then \
		lci tests/basic.lol; \
	else \
		echo ""; \
		echo "O NOES! U NOT HAS LCI (LOLCODE INTERPRETAH)"; \
		echo ""; \
		echo "2 INSTALL:"; \
		echo "  git clone https://github.com/justinmeza/lci.git"; \
		echo "  cd lci && cmake . && make && sudo make install"; \
		echo ""; \
		echo "OR ON MAC:"; \
		echo "  brew install lci"; \
		echo ""; \
	fi

clean:
	@echo "CLEANIN UP..."
	rm -f test_lolcode.db
	@echo "ALL UR ARTIFACTS R BELONG 2 /DEV/NULL"

help:
	@echo "HAI 1.2"
	@echo ""
	@echo "VISIBLE \"REDLITE LOLCODE SDK HALP\""
	@echo ""
	@echo "COMMANDZ:"
	@echo "  make build  - BTW nothin 2 build actually"
	@echo "  make test   - IM IN YR TESTS, TESTIN YR DATABASE"
	@echo "  make clean  - MAEK ARTIFACTS GO AWAY"
	@echo "  make help   - U R LOOKIN AT IT"
	@echo "  make hai    - SAY HAI"
	@echo "  make kthxbye - SAY KTHXBYE"
	@echo ""
	@echo "KTHXBYE"

kthxbye:
	@echo "KTHXBYE"
	@echo ""
	@echo "  ╱|、"
	@echo "(˚ˎ 。7"
	@echo " |、˜〵"
	@echo " じしˍ,)ノ"
	@echo ""
	@echo "CEILING CAT SEZ BAI"
