HAI 1.2
  BTW ===========================================
  BTW REDLITE LOLCODE TEST SUITE
  BTW IM IN YR TESTS, TESTIN YR DATABASE
  BTW ===========================================

  CAN HAS REDLITE?

  I HAS A FAILZ ITZ 0
  I HAS A PASSEZ ITZ 0

  VISIBLE "=== STARTIN TESTZ ==="
  VISIBLE ""

  BTW --- SETUP ---
  VISIBLE "OPENIN DATABASE..."
  I HAS A DB ITZ REDLITE OPEN YR "test_lolcode.db"
  VISIBLE "DATABASE OPEND! KTHX"
  VISIBLE ""

  BTW --- TEST 1: SET AN GET ---
  VISIBLE "TEST 1: SET AN GET"
  REDLITE'Z DB CALLIN SET WIF "kitteh" AN "HAPPEH"
  I HAS A RESULT ITZ REDLITE'Z DB CALLIN GET WIF "kitteh"
  BOTH SAEM RESULT AN "HAPPEH", O RLY?
    YA RLY
      VISIBLE "  PASS: GOT HAPPEH KITTEH"
      PASSEZ R SUM OF PASSEZ AN 1
    NO WAI
      VISIBLE "  FAIL: EXPECTED HAPPEH, GOT " AN RESULT
      FAILZ R SUM OF FAILZ AN 1
  OIC
  VISIBLE ""

  BTW --- TEST 2: GET MISSIN KEY ---
  VISIBLE "TEST 2: GET MISSIN KEY"
  I HAS A RESULT2 ITZ REDLITE'Z DB CALLIN GET WIF "invisible_kitteh"
  BOTH SAEM RESULT2 AN NOOB, O RLY?
    YA RLY
      VISIBLE "  PASS: NOOB 4 MISSIN KEY"
      PASSEZ R SUM OF PASSEZ AN 1
    NO WAI
      VISIBLE "  FAIL: EXPECTED NOOB, GOT SOMTHIN"
      FAILZ R SUM OF FAILZ AN 1
  OIC
  VISIBLE ""

  BTW --- TEST 3: INCR ---
  VISIBLE "TEST 3: INCR"
  REDLITE'Z DB CALLIN SET WIF "countah" AN "0"
  I HAS A COUNT1 ITZ REDLITE'Z DB CALLIN INCR WIF "countah"
  I HAS A COUNT2 ITZ REDLITE'Z DB CALLIN INCR WIF "countah"
  I HAS A COUNT3 ITZ REDLITE'Z DB CALLIN INCR WIF "countah"
  BOTH SAEM COUNT3 AN 3, O RLY?
    YA RLY
      VISIBLE "  PASS: COUNTAH IZ 3"
      PASSEZ R SUM OF PASSEZ AN 1
    NO WAI
      VISIBLE "  FAIL: EXPECTED 3, GOT " AN COUNT3
      FAILZ R SUM OF FAILZ AN 1
  OIC
  VISIBLE ""

  BTW --- TEST 4: DEL ---
  VISIBLE "TEST 4: DEL"
  REDLITE'Z DB CALLIN SET WIF "2b_deleted" AN "BAIIII"
  REDLITE'Z DB CALLIN DEL WIF "2b_deleted"
  I HAS A GONE ITZ REDLITE'Z DB CALLIN GET WIF "2b_deleted"
  BOTH SAEM GONE AN NOOB, O RLY?
    YA RLY
      VISIBLE "  PASS: KEY IZ GONE"
      PASSEZ R SUM OF PASSEZ AN 1
    NO WAI
      VISIBLE "  FAIL: KEY STILL DERE"
      FAILZ R SUM OF FAILZ AN 1
  OIC
  VISIBLE ""

  BTW --- TEST 5: HSET AN HGET ---
  VISIBLE "TEST 5: HSET AN HGET (BUCKITZ)"
  REDLITE'Z DB CALLIN HSET WIF "mah_buckit" AN "flavor" AN "cheezburger"
  I HAS A FLAVOR ITZ REDLITE'Z DB CALLIN HGET WIF "mah_buckit" AN "flavor"
  BOTH SAEM FLAVOR AN "cheezburger", O RLY?
    YA RLY
      VISIBLE "  PASS: I CAN HAS CHEEZBURGER"
      PASSEZ R SUM OF PASSEZ AN 1
    NO WAI
      VISIBLE "  FAIL: NO CHEEZBURGER 4 U"
      FAILZ R SUM OF FAILZ AN 1
  OIC
  VISIBLE ""

  BTW --- TEST 6: LPUSH AN LPOP ---
  VISIBLE "TEST 6: LPUSH AN LPOP (CONGA LIEN)"
  REDLITE'Z DB CALLIN LPUSH WIF "conga" AN "kitteh1"
  REDLITE'Z DB CALLIN LPUSH WIF "conga" AN "kitteh2"
  REDLITE'Z DB CALLIN LPUSH WIF "conga" AN "kitteh3"
  I HAS A FIRST ITZ REDLITE'Z DB CALLIN LPOP WIF "conga"
  BOTH SAEM FIRST AN "kitteh3", O RLY?
    YA RLY
      VISIBLE "  PASS: KITTEH3 WUZ FIRST IN LIEN"
      PASSEZ R SUM OF PASSEZ AN 1
    NO WAI
      VISIBLE "  FAIL: WRONG KITTEH"
      FAILZ R SUM OF FAILZ AN 1
  OIC
  VISIBLE ""

  BTW --- TEST 7: SADD AN SISMEMBER ---
  VISIBLE "TEST 7: SADD AN SISMEMBER (UNIQUE KITTEHZ)"
  REDLITE'Z DB CALLIN SADD WIF "kitteh_club" AN "fluffy"
  REDLITE'Z DB CALLIN SADD WIF "kitteh_club" AN "whiskers"
  I HAS A IZ_MEMBER ITZ REDLITE'Z DB CALLIN SISMEMBER WIF "kitteh_club" AN "fluffy"
  BOTH SAEM IZ_MEMBER AN WIN, O RLY?
    YA RLY
      VISIBLE "  PASS: FLUFFY IZ IN DA CLUB"
      PASSEZ R SUM OF PASSEZ AN 1
    NO WAI
      VISIBLE "  FAIL: FLUFFY NOT FOUND"
      FAILZ R SUM OF FAILZ AN 1
  OIC
  VISIBLE ""

  BTW --- TEST 8: EXISTS ---
  VISIBLE "TEST 8: EXISTS"
  REDLITE'Z DB CALLIN SET WIF "i_exist" AN "YEP"
  I HAS A DERE ITZ REDLITE'Z DB CALLIN EXISTS WIF "i_exist"
  BOTH SAEM DERE AN WIN, O RLY?
    YA RLY
      VISIBLE "  PASS: KEY EXISTZ"
      PASSEZ R SUM OF PASSEZ AN 1
    NO WAI
      VISIBLE "  FAIL: KEY SHUD EXIST"
      FAILZ R SUM OF FAILZ AN 1
  OIC
  VISIBLE ""

  BTW --- CLEANUP ---
  VISIBLE "CLEANIN UP..."
  REDLITE'Z DB CALLIN FLUSHDB
  REDLITE'Z DB CALLIN CLOSE
  VISIBLE ""

  BTW --- RESULTZ ---
  VISIBLE "=== TEST RESULTZ ==="
  VISIBLE "PASSEZ: " AN PASSEZ
  VISIBLE "FAILZ: " AN FAILZ
  VISIBLE ""

  BOTH SAEM FAILZ AN 0, O RLY?
    YA RLY
      VISIBLE "ALL UR TESTS R BELONG 2 US"
      VISIBLE "GREAT SUCCESS!"
    NO WAI
      VISIBLE "U HAS FAILUREZ :("
      VISIBLE "SAD KITTEH IZ SAD"
  OIC

KTHXBYE
